{% set name = "twinstop" %}
{% set version = load_setup_py_data().version %}

package:
  name: "{{ twinstop }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - blast >= 2.12.0
    - easyterm >= 1.0.0
    - easybioinfo >= 0.2.1
    - extend_orfs >= 0.0.27
    - file-chunk-iterators >= 0.0.1
    - pyranges >= 0.0.120
    - pandas >= 1.3.5
    - multiprocess >= 0.70.14
    - numpy >= 1.21.5
    - mafft >= 7.505
 

about:
  home: "https://github.com/Sergio-Sanchez96/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Description of project"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti
